### ISSUE TITLE
文字未上屏時按「發送」，未上屏的文字會被保留

### ISSUE THREAD

**Issue by goofyz** [osfans/android-rime#1134]
**Describe the bug**
文字未上屏時，點擊「發送」按鈕後，文字會被發送，但未上屏的文字還是保留在輸入狀態。

**To Reproduce**
Steps to reproduce the bug:
1. Go to 「鍵盤設定」>「嵌入式編輯」>選擇「輸入碼」(or 首選/編碼)
2. 在訊息的 app ，輸入文字，如 「vnd」，不要按 space 上屏
3. 在此狀態下按「發送」按鈕
4. 「vnd」文字會被發送，但在文字欄位還是有「vnd」

**Expected behavior**
文字欄位應該要被清空

**Screenshots**
![2023-12-04 16 50 09](https://github.com/osfans/trime/assets/2428334/ec4c8678-3864-490f-a920-75853ed8e0ad)

**Smartphone (please complete the following information):**
 - Version: 3.2.15

**Comment by Bambooin** [comment]
Seems the root cause is librime: https://github.com/rime/librime/issues/761

**Comment by goofyz** [comment]
應該不是，因為該「發送」按鈕不是 rime/TRIME 的。
我想我已找到問題所在，測試多一會後再 PR 。☺
