### ISSUE TITLE
最新版本无法使用拼音和繁标显示

### ISSUE THREAD

**Issue by atlanticfirst** [osfans/android-rime#1466]
### 摘要 / Summary

更新到最新版本以后，  显示拼音和繁体标注失效了，但奇怪的是显示Emoji的功能却沒有失效
filters:
    - simplifier@emoji    #Emoji
    - simplifier@pinyin     #显示拼音
    - simplifier@s2tinfo    #显示繁体标注

### 重现步骤 / Steps to Reproduce

输入任意编码

### 预期行为 / Expected Behavior

候选栏的文字会带有拼音或者繁标

### 附加信息 / Additional Context

老版本正常

### 系统版本 / OS Version

安卓

### 应用版本 / App Version

f-droid最新版

### 构建信息 / Build Information

无

**Comment by WhiredPlanck** [comment]
1. 请先尝试最新每夜版
2. 检查配置文件夹中的 opencc 文件夹是否消失。你可以在 app 中的“配置管理”中点击“恢复出厂设置”，勾选“opencc”后点击确定来恢复 app 内置的 opencc 数据。

**Comment by atlanticfirst** [comment]
> 1. 请先尝试最新每夜版
> 2. 检查配置文件夹中的 opencc 文件夹是否消失。你可以在 app 中的“配置管理”中点击“恢复出厂设置”，勾选“opencc”后点击确定来恢复 app 内置的 opencc 数据。

comment_on_top: true如果设置提示在上方就完全无法显示，如果false拼音或者繁体提示就会正常出现在候选项右方。请问这种情况该怎么解决啊

**Comment by WhiredPlanck** [comment]
> > 1. 请先尝试最新每夜版
> > 2. 检查配置文件夹中的 opencc 文件夹是否消失。你可以在 app 中的“配置管理”中点击“恢复出厂设置”，勾选“opencc”后点击确定来恢复 app 内置的 opencc 数据。
> 
> comment_on_top: true如果设置提示在上方就完全无法显示，如果false拼音或者繁体提示就会正常出现在候选项右方。请问这种情况该怎么解决啊

请先尝试最新每夜版，这个问题应该已经修好了
