### ISSUE TITLE
Change YAML-CPP version for support "merge" key

### ISSUE THREAD

**Issue by Lak4CYUT** [osfans/android-rime#538]
**Is your feature request related to a problem? Please describe.**
原版的 YAML-CPP 並不 support "merge" key，作者看來有些他自己的考量。
(ref to :https://github.com/jbeder/yaml-cpp/issues/41)
Merge key 的支援可以讓 YAML 定義檔更簡潔一些，考量到很多鍵盤的 "key" 都是重覆的功能重覆的設定。
是否可以考慮加入支援？
**Describe the solution you'd like**
目前 Github 上有一個 fork 版本有提供 merge key 的支援，且有跟到非常新的版本。
https://github.com/loot/yaml-cpp/tree/merge-key-support
可以考慮換用這個版本來提供 merge key 的支援。

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Bambooin** [comment]
Last yaml 1.2 revesion does not support merge key feature, so I think we should keep it.
