### ISSUE TITLE
滑动在输入过快时会被误触

### ISSUE THREAD

**Issue by iovxw** [osfans/android-rime#553]
**Describe the bug**

在输入特别快时，如果屏幕上同一时间停留了多根手指（没来得及抬起），会错误触发按键的滑动操作

**To Reproduce**
Steps to reproduce the bug:

以默认的 `qwerty` 布局为例

其中 `j` 键的配置为：

https://github.com/osfans/trime/blob/712e521a947d1deaa733c218bce9c4a5c4b7f1b2/app/src/main/assets/rime/trime.yaml#L1162

1. 按下 `j`
2. 按下左侧同行任意按键（视频内为 `s`）
3. 松开左侧按键（这时 `s` 被输出）
3. 松开 `j` （这时 `}` 被输出，是 `swipe_right` 的配置）

以上操作要在长按触发延迟内完成，参见下方视频

**Expected behavior**

**Log**
If applicable, add crash log to quick focus your problem.

**Screenshots**

视频为三倍慢速

https://user-images.githubusercontent.com/6631572/138122190-95df8bc8-919f-419e-9178-2f2d73e289c3.mp4

**Smartphone (please complete the following information):**
 - Device: Nexus 5
 - OS: Android 11
 - Version: 8ea42b8

**Additional context**
cc #534 #537 @tumuyan

**Comment by tumuyan** [comment]
确实存在这个问题.
从键盘设计角度讲，y>x的按键首选还是长按，其次是上下滑动，左右滑动操作不便，也更容易触发你反馈的问题（毕竟纵向按键少，手指也不便纵向交叠对吧）

如果在优化触摸之前的版本都没有这个问题，那解决起来比较简单。
如果之前也存在，情况就很麻烦了。

**Comment by iovxw** [comment]
确认了在 #537 之前没有这个问题

**Comment by tumuyan** [comment]
...网太差了，还是百度云吧
理论上解决了这类问题，恢复到了pr提交之前的水平
链接: https://pan.baidu.com/s/15LsH276rIK7EVGygG4ccGA 提取码: yyeu

**Comment by tumuyan** [comment]
@iovxw 你测试过我编译的包了嘛？

**Comment by iovxw** [comment]
抱歉之前没有时间

刚刚试了确实解决了
