### ISSUE TITLE
状态栏，悬浮窗，候选栏——无法适应主题背景（小鹤主题）

### ISSUE THREAD

**Issue by yanhuacuo** [osfans/android-rime#554]
##「状态栏背景色」不能适应「主题背景色」

![pic](https://github.com/yanhuacuo/98wubi-weasel/raw/master/demo/QQ%E5%9B%BE%E7%89%8720211019213655.jpg)

![pic](https://github.com/yanhuacuo/98wubi-weasel/raw/master/demo/QQ%E5%9B%BE%E7%89%8720211019213702.jpg)

## 正常如下：

![pic](https://github.com/yanhuacuo/98wubi-weasel/raw/master/demo/QQ%E5%9B%BE%E7%89%8720211019214054.jpg)

![pic](https://github.com/yanhuacuo/98wubi-weasel/raw/master/demo/QQ%E5%9B%BE%E7%89%8720211019214047.jpg)

**Comment by rainhear** [comment]
- 新近版本引入了全新的參數項控制 `候選欄背景色`，第三方主題需及時跟進增設，詳情可閱讀 #528

**Comment by yanhuacuo** [comment]
> * 新近版本引入了全新的參數項控制 `候選欄背景色`，第三方主題需及時跟進增設，詳情可閱讀 [键盘字体和尺寸异常 #528](https://github.com/osfans/trime/issues/528)

感谢，这部分总算有解决办法了，后面就是关注「键盘功能标签字体偏大」的解决办法啦。

**Comment by rainhear** [comment]
`fallback_colors` 下游節點增設的參數項：

- `root_background` 鍵盤與候選欄基底背景
- `candidate_background` 候選欄背景
- `liquid_keyboard_background` 液態鍵盤背景
- `long_text_back_color` 剪貼板按鍵背景

也可在 `preset_color_schemes/xxx` 中二次定義，
其中 `root_background` 在視覺上可被 `candidate_background` `keyboard_back_color` 覆蓋。
